### ISSUE TITLE
App cannot find any key that appear on source language page

### ISSUE THREAD

**Issue by serbancoroiu** [localazy/ios-demo#1]
Hi 👋 ,

I am trying to integrate the Localazy SDK in my app. I have uploaded the `en` keys and translations on Localazy using the CLI integration. Now i want to use SDK to be able to change app string without doing another version release. 

So below you can see that my keys are visible in source language page: 
![image](https://user-images.githubusercontent.com/48278459/140658083-b2c507ba-38e4-4063-8a77-78b9e0ee19b2.png)

And when i'm trying to access any key from the app i am receiving this message: 
![image](https://user-images.githubusercontent.com/48278459/140658130-26dccc7a-1db7-47ae-9019-de5175fb3635.png)

I have checked if the app connected to my Localazy app using the `Localazy.shared.getProjectUrl()` and it points to the correct url. 

Thanks for help 🙏

**Comment by honzabilek4** [comment]
Hey 👋 
I'd be happy to help, but I would just need more details about your app. 

1. Which SDK version do you use?
2. How do you resolve the translations in your code?
3. Could you please share a link to your project on Localazy?

If any of this is private, you can also send a message to team@localazy.com

Cheers.

**Comment by serbancoroiu** [comment]
Hi, 

I found the issue, there was a payment issue and i was on free tier 🤦 .

**Comment by honzabilek4** [comment]
Great!
There's a limit of 200 keys in the free tier. If you're over the limit, the publishing of changes gets disabled, and therefore the described problem appeared -> The key really didn't exist.
I'll pin the issue if anyone else comes across the same problem.

**Comment by neetrath** [comment]
I've setup only 2 key and it still shows "Key ID not found for key: hello"
